# Generated by Django 4.2.11 on 2024-03-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('ammo_id', models.AutoField(primary_key=True, serialize=False)),
                ('ammo_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('serial', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('ammo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ammo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.model')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_no', models.AutoField(primary_key=True, serialize=False)),
                ('rent_date_start', models.DateTimeField()),
                ('rent_date_end', models.DateTimeField()),
                ('rented_uav_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.uav')),
                ('who_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
